- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install packages
    yum: name={{item}} state=present
    loop:
    - git
    - docker
    - tree
  - name: Start docker
    service: name=docker state=started
  - name: Clone a git repo
    git: repo=https://github.com/edureka-devops/projCert.git dest=/tmp/gitrepo
  - name: Build docker file
    command: chdir=/tmp/gitrepo docker build -t myimageaddr:v1 .
  - name: Run the image
    command: docker run -itd -P edurekaProj:v1
