---

- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install packages
    yum: name={{item}} state=present
    loop:
    - git
    - docker
    - tree
  - name: Start docker
    service: name=docker state=started
  - name: Clone a git repo
    git: repo=https://github.com/NarasimhaluM/myDevopsProject.git dest=/var/www/html
  - name: Build docker file
    command: chdir=/var/www/html docker build -t mydevopsproj:v1 .
  - name: Run the image
    command: docker run -itd -P mydevopsproj:v1
