- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install packages
    yum: name={{item}} state=present
    loop:
    - git
    - docker
    - tree
  - name: Start docker
    service: name=docker state=started
  - name: Pull the image
    command: docker pull devopsedu/webapp
  - name: Run the image
    command: docker run --name myproj -d -p 8282:80 devopsedu/webapp
