- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install packages
    yum: name={{item}} state=present
    loop:
    - git
    - docker
    - tree
  - name: Start docker
    service: name=docker state=started
  - name: Run the image
    command: docker service create --name mydevproj -p 8282:80 --replicas 2 devopsedu/webapp:v1
